import type { NextPage } from 'next'
import Head from 'next/head'
import HomeView from "views/Home";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SMECS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <HomeView/>
    </>
  )
}

export default Home
